### ISSUE TITLE
Wrong go back order in a specific condition

### ISSUE THREAD

**Issue by MarcAnt01** [UnigramDev/Unigram#1061]
How to reproduce:
1. Open reply banner quoting a message;
2. Press forward to forwared the message.

When going back (eg. esc) the reply banner will be closed before forward menu despite having been opened before

**Comment by FrayxRulez** [comment]
@MarcAnt01 I don’t understand

**Comment by MarcAnt01** [comment]
@FrayxRulez As you have implemented touchpad gestures, just swipe left and right to reproduce

**Comment by platy11** [comment]
I'm also encountering this issue:

**Steps to reproduce:**
1. Have a reply drafted
2. Either preview an image in fullscreen, or open the 'send to' forwarding dialog, 'send files' dialog, 'edit media' dialog, 'send location' dialog, 'message within chat' searchbar or 'find chat' searchbar
3. Press the Esc key

**Expected Behaviour:**
The pane/dialog opened in step 2 is closed, as it was opened more recently and is focused/in the foreground.

**Actual Behaviour:**
The reply is cancelled. The dialog/pane is closed if Esc is pressed again.

**Version Details:**
Reproduced on:
Windows 10 1903, Unigram 4.2.5263.0
Windows 10 2004, Unigram 4.2.5263.0

**Comment by FrayxRulez** [comment]
Was fixed some day
