### ISSUE TITLE
Option to decide whether to use markdown or WYSIWIG

### ISSUE THREAD

**Issue by FrayxRulez** [UnigramDev/Unigram#1426]
**Why?**
As many users prefer markdown over WYSIWIG we might want to offer an option to choose whether to use one or the other when editing messages.

**What?**
Research on this topic and decide if this feature should be implemented

**Comment by simonebarbieri** [comment]
I'm italian, and in italian (but I'm sure many other languages have the same problem) many words use the accent. I add the "`" symbol to mark them (as I am using an english keyboard, I don't have the accented vowels keys). Because of markdown used by default, whenever the message I'm writing has 2 or more accents, those are deleted and that portion of the message is sent as monospace. An option to disable markdown would be really appreciated!
