### ISSUE TITLE
MP3 player improvements

### ISSUE THREAD

**Issue by abh-oss01** [UnigramDev/Unigram#1543]
Make the MP3 player into a full fledged one, with the features such as queuing, rearranging the songs, multiple selection..etc
Basically like telegram X.

**Comment by cewbdex** [comment]
@abh-oss01

**Comment by abh-oss01** [comment]
@cewbdex what

**Comment by MarcAnt01** [comment]
No, as written in contributing guidelines Unigram follows official guidelines

**Comment by abh-oss01** [comment]
doesn't mean you have to follow TD*****p

**Comment by MarcAnt01** [comment]
Please read that file before complaining

**Comment by FrayxRulez** [comment]
I told to @abh-oss01 to open the ticket

**Comment by MarcAnt01** [comment]
Ah, all right then😂😂

**Comment by FrayxRulez** [comment]
[ ] Volume slider (`?`)

**Comment by abh-oss01** [comment]
what?
why is everything deleted?

**Comment by MarcAnt01** [comment]
> what?
> why is everything deleted?

Why not

**Comment by FrayxRulez** [comment]
> what?
> why is everything deleted?

To clean up the useless discussion you had here

**Comment by NotLT** [comment]
> * [ ]  Volume slider (`?`)

Volume slider would be useful, as the only way to make Unigram more quiet is to lower volume of the whole system (There is an option in sound mixer but it is too deep in system settings).
Would also be cool to sync it with the video volume so that the user would have consistent knowledge of the volume level across any audio emitted from Unigram.

**Comment by Fen0MeN102** [comment]
@NotLT Sound mixer isn't as deep as you think

**Comment by FrayxRulez** [comment]
Done in https://github.com/UnigramDev/Unigram/commit/fd0e2a5261bf91ae30e312fee5d4338c6ff56480
