### ISSUE TITLE
Add message ignore for blocked users in group chats

### ISSUE THREAD

**Issue by WeFenFinit** [UnigramDev/Unigram#1834]

**Comment by MarcAnt01** [comment]
Can you explain the feature you're asking for?

**Comment by abh-oss01** [comment]
pls don't add this :)

**Comment by WeFenFinit** [comment]
I want to hide blocked user massages in group chat.

@abh-oss01 are you one of this trolling people who don't want to be ignored?

**Comment by MarcAnt01** [comment]
@abh-oss01 please use downvotes or explain eventual drawbacks

@WeFenFinit I understand you might be frustrated by some messages, but keep in mind that there is a code of conduct for this repo

**Comment by MarcAnt01** [comment]
As for the feature, official clients don't have it, so it won't be considered

**Comment by abh-oss01** [comment]
@WeFenFinit it's a very rude and unnecessary feature, which is only found on obscure unofficial android clients like Nekogram .. etc
It is not necessary on a high level desktop app such as Unigram, because you can always choose not answering the person(s) in consideration.
and, about the thing you asked me --> :)

**Comment by abh-oss01** [comment]
@MarcAnt01 downvotes? how?
