### ISSUE TITLE
Re-add old themes

### ISSUE THREAD

**Issue by kurmachu** [UnigramDev/Unigram#1838]
I personally like the old "System" dark theme more than night, and I'm sure others will appreciate the option to use their old themes without spending hours using the custom theme editor from memory. You could hide them under "Show All Themes" if needed.

**Comment by FrayxRulez** [comment]
Re-adding old "System" themes isn't an option, because they forced me to keep some old and legacy code that I happily removed, as it prevented some better themes integration (such as following system settings, to say one).

The app isn't able to follow system settings at the moment, as I'm still trying to figure out what's the right UX for this, in the meanwhile you can use auto night mode, that should be a perfect replacement.
