### ISSUE TITLE
Memory leaks after long sessions

### ISSUE THREAD

**Issue by ze0ss** [UnigramDev/Unigram#1892]

**Comment by MarcAnt01** [comment]
For this kind of reports, attach crash logs or specify the name of your device so that it can be found via App Center

**Comment by abh-oss01** [comment]
No crash logs because I don't record them, and the crashes are absolutely random, so no point in Verbose logging because I wouldn't know when a crash would take place, sometimes a crash would never happen but the logger would keep logging everything.
.... 
and what about the high memory usage after using the app for a long time?

**Comment by MarcAnt01** [comment]
I am talking about crash dumps, as for memory leaks after a long period it's a known bug.

**Comment by MarcAnt01** [comment]
Is this report about memory leaks or random crashes tho?

**Comment by abh-oss01** [comment]
lol both

**Comment by MarcAnt01** [comment]
Do random crashes happen ONLY after long sessions?

**Comment by abh-oss01** [comment]
> I am talking about crash dumps, as for memory leaks after a long period it's a known bug.

I know what you're talking about, and my answer still stands :)
Like I said, how could I allow tdlib to verbose log my activities if I'm not sure if app is going to crash or not, I could never have a crash at all, who knows.

**Comment by MarcAnt01** [comment]
Crash dumps aren't connected to TDLib at all

**Comment by abh-oss01** [comment]
> Do random crashes happen ONLY after long sessions?

ofcourse, yes

**Comment by FrayxRulez** [comment]
Lot of leaks have been fixed lately, especially when switching between accounts
