### ISSUE TITLE
Images always get sent as file

### ISSUE THREAD

**Issue by Bygrilinho** [UnigramDev/Unigram#1939]
![image](https://user-images.githubusercontent.com/20670349/89030635-3a9fbb80-d307-11ea-8fde-b013b2e103e8.png)
This is happening with any image I try to post, be it via clipboard, drag and drop, or selecting "gallery" option from Unigram.

**Comment by MarcAnt01** [comment]
This is the default behavior for very wide pictures

**Comment by Bygrilinho** [comment]
> This is the default behavior for very wide pictures

It's happening for every picture
This, for example, is this wide? It's sending as file:
![image](https://user-images.githubusercontent.com/20670349/89035842-fbc33300-d311-11ea-8586-9d07889a6fb0.png)

**Comment by MarcAnt01** [comment]
All right, reopening then

**Comment by FrayxRulez** [comment]
I can't reproduce.

**Comment by Bygrilinho** [comment]
After formatting my PC (uninstall didn't solve), it stopped happening, so idk

**Comment by ShikiGami** [comment]
I'm having this problem now. It started to happen suddenly with all images, including screen shots. Before I would get an option to send as file or as picture, now it just goes as picture like in the first post.

**Comment by AsrorbekDev** [comment]
@ShikiGami which photo?

**Comment by ShikiGami** [comment]
![image](https://user-images.githubusercontent.com/3926168/147871891-3edff963-f61b-4f70-b504-50cdd8108792.png)
This is all I get when I try to send any picture of any format and any size. For example, for this one i just copied the picture from my profile that appear in this page, and did a Ctrl+V on some chat.

**Comment by FrayxRulez** [comment]
What happens if you try to set a different profile picture?

**Comment by ShikiGami** [comment]
> What happens if you try to set a different profile picture?

It just gets updated to that. The profile picture thing was just about copying any random picture into a chat. For this test I copied the picture from my github profile as it appears in this page into some random chat.

I used to copy a lot of picture, so that my contacts would rapidly preview look at them in their chat window, but because they now can only be sent as files, they have to open the file in order to see those images.

**Comment by makisukurisu** [comment]
By looking at image name, that doesn't look like GitHub profile picture. More like a screenshot.

**Comment by FrayxRulez** [comment]
Most likely it won't work, but could you try to run this command in PowerShell?
`Get-AppXPackage | Foreach {Add-AppxPackage -DisableDevelopmentMode -Register "$($_.InstallLocation)\AppXManifest.xml"}`

**Comment by ShikiGami** [comment]
> By looking at image name, that doesn't look like GitHub profile picture. More like a screenshot.

It was a copy using the right click "Copy Image" function that puts the image into the windows clipboard, and works similar to how screenshots work.

> Most likely it won't work, but could you try to run this command in PowerShell?
> `Get-AppXPackage | Foreach {Add-AppxPackage -DisableDevelopmentMode -Register "$($_.InstallLocation)\AppXManifest.xml"}`

I just tried it, and the file behavior is still the same.

**Comment by ShikiGami** [comment]
Just for comparison sake, this is what happens when I try to paste the same thing on the Official Telegram Desktop application.
![image](https://user-images.githubusercontent.com/3926168/148013883-a9985e75-e09b-4261-9c48-f4a6b116483a.png)

**Comment by FrayxRulez** [comment]
This was caused by the fact that Unigram used the mime type of the file to check whether this is a image.
Because mime type lives in the registry and some non very polite software kang it, the app was unable to recognize the files.
The logic was changed at some point to rather use the files extension, and this issue should no longer exist.
