### ISSUE TITLE
Acrylic Background

### ISSUE THREAD

**Issue by livejamie** [UnigramDev/Unigram#1993]
Would really love the option to use Blurred Acrylic backgrounds, similar to what Notepads does

https://github.com/JasonStein/Notepads

![image](https://user-images.githubusercontent.com/49513/92981402-81c4b480-f44e-11ea-982c-279b37e2b6cd.png)

**Comment by codehz** [comment]
Maybe also add Mica Material too? it looks cleaner and more suitable for applying to whole window in my opinion.

**Comment by FrayxRulez** [comment]
App now uses Mica

**Comment by livejamie** [comment]
Sorry if I misunderstand, Is there a way to have the blurred acrylic background like this ticket was mentioning?

**Comment by MarcAnt01** [comment]
No, we’re sorry, but what you suggest is against every design guideline, even when most apps were using it wasn’t meant for the whole app background. Background acrylic (not in-app) is also not recommended any longer now

**Comment by lomarence** [comment]
@MarcAnt01 would love to see a little acrylic backdrop happening in the unigram app even if it's only for the chats on the left side as shown here:
https://dribbble.com/shots/14719274-Telegram-Desktop-macOS-Big-Sur-redesign

Why is it against every design guideline to have acrylic backdrop? What is the preferred design guideline for Mica and Acrylic?

**Comment by FrayxRulez** [comment]
> Why is it against every design guideline to have acrylic backdrop? What is the preferred design guideline for Mica and Acrylic?

Acrylic is slow because it requires real time rendering of the effect and it's not recommended to be used for large surfaces. Additionally (at least in my opinion) it isn't great in terms of contrast, especially in complex UI scenarios (as it would be in the chat list). Additionally, Microsoft itself kind of moved from using Acrylic in this kind of scenarios and the way to go is Mica.

**Comment by lomarence** [comment]
@FrayxRulez so why is MacOs using acrylic effects so much? It's really backed in the OS and almost every app uses this effect?

**Comment by FrayxRulez** [comment]
I don't know, Unigram is a Windows software, not a macOS one, consequently we respect Microsoft guidelines and not Apple ones.

**Comment by lomarence** [comment]
@FrayxRulez okay I understand. But why does the Unigram team hosts a design contest to feature in future updates where the winning person Sunny Swan (https://sunnyswan296822.invisionapp.com/console/share/G6EYDAQZ5F3) and also the 2nd place Groovy Ladybird (https://www.figma.com/file/Ei6xUhhDvAshU06PAtGO1P/Codename-Micagram-(Unigram-Redesign)?type=design&node-id=178-100150&mode=design&viewport=394%2C48%2C0.87) rely heavly on acrylic surfaces? Did the design guidelines changed since then?

**Comment by makisukurisu** [comment]
@Oronhyatekha To be fair, the first one uses acrylics in pretty subtle ways, that can be ignored sometimes (e.g - the file/image sending UI having acrylic background). Other times (at least to me) it looks like a double pass of Mica, or Mica with a mix in of a color. Maybe not technically possible, but that's how the designer envisions it.

And the second one doesn't use acrylic all that often. To be honest, it's almost precisely how Unigram looks right now in the real world. With the exception of some screens or features. (Group/P2P calls, settings are a bit different, video notes don't have a preview yet)

The more general answer to your question is:
Design competitions, and designs in general, don't have to follow all the guidelines.

Even real world apps don't have to follow all of them with 100% accuracy.
Design competitions are mainly a source of great fresh ideas, and inspirations. Because most of the time they aren't bounded by the available building blocks. (Like the first contestant, using who knows how many types and variants of blur, that isn't that easy to replicate in UWP)
This may encourage out of the box thinking, to create something unique, or bring an idea from a design, improving the app's look (which it did!)

P.S. The competition technically was held by the Telegram team

**Comment by lomarence** [comment]
@makisukurisu Okay I get it. Thank you for the answer. Didn’t know that the contest was from the telegram team. Maybe glassmorphism doesn’t stay this long in the future but I like it very much also in the way Apple uses it and Microsoft adapted it. Appreciate your work.
