### ISSUE TITLE
Make instant view more compact

### ISSUE THREAD

**Issue by MarcAnt01** [UnigramDev/Unigram#2005]
Add some padding on both sides to make reading easier on larger screens

**Comment by jvlianodorneles** [comment]
Excellent suggestion!

"A wider leading makes it easy for the eye to follow the line. A very wide leading, however, disturbs reading because the eye has to travel long distances between the lines. In addition, the reader becomes uncomfortable because of the visible striped effect.

The literature gives different values for good line lengths, depending on the author. To some extent, this is related to the author’s native language. Since the eye usually jumps from word to word, short words make this task easier. Across all languages and fonts, **a line length of 60 to 70 characters, including spaces and punctuation, forms a usable compromise**. Longer line lengths should only be considered for highly-developed readers who spend many hours a day reading. But even then, line lengths beyond 80 characters are unacceptable."

**Comment by MarcAnt01** [comment]
Any update on this?

**Comment by FrayxRulez** [comment]
@MarcAnt01 I just laid on my bed
