### ISSUE TITLE
Feature request. Deleting old messages by timer in normal chats 

### ISSUE THREAD

**Issue by ghost** [UnigramDev/Unigram#2030]
I think most of Unigram users choose this app for security feature as secret chat for desktop. So this users as security focused.

I think very good idea add some security features from secret chats to normal chats. Most important feature is not cryptographic protection. I'm using secret chats for "timer deleting" feature.  However it's very easy to implement this security feature in normal chats in Unigram.

**Comment by Kenya-West** [comment]
Deletion after some time is a feature baked by Telegram API in secret chat, the app doesn't care about it. You are asking for same feature but in different (client-side) implementation. This will require some work and effort to keep the code abstract/consistent/resuable for TDLib API... I guess there are not many chances to get this feature approved.

**Comment by delmoster** [comment]
The application already supported bulk deleting of messages. However you need to select messages manually. It's more complex code than simple deleting of messages for some time range. 

I agree with mr. Durov that deleting of old messages most important security feature. Typical "leaks" based on very old talks with some unreliable persons. Therefore Telegram supported automatic deletion of unused account by time period. However if you are using Telegram permanently then you don't have any automatic features for deleting old messages.

Also automatic deleting of old messages should be improve Unigram speed and reliability because messages base will be very small.

**Comment by MarcAnt01** [comment]
This feature isn't in official clients, so it won't be considered at least at the moment
