### ISSUE TITLE
RTL issue

### ISSUE THREAD

**Issue by mladenb** [UnigramDev/Unigram#2174]
I'm not sure if this is a bug or a feature, but normal joins to the group are announced usually like this:
![image](https://user-images.githubusercontent.com/6103881/101467692-ef478a80-3942-11eb-8181-d0b0dc3b904c.png)
and today we had a user joining the group with Unigram displaying it like this:
![image](https://user-images.githubusercontent.com/6103881/101467731-fff80080-3942-11eb-8847-dbc2f2dbff81.png)

Apparently, that username is in either arabic or a similar language which uses RTL (right-to-left) writing, but it seems Unigram got confused with that one.

**Comment by FrayxRulez** [comment]
I think that this isn't neither a bug or a feature, but just how (badly) RTL text works.
I'm pretty sure that's simply how Windows renders that text when it has no other references to choose text directionality.
Microsoft Edge does the same thing when you paste the text in the address bar:
![image](https://user-images.githubusercontent.com/8152849/101468664-020e8f00-3944-11eb-9a8b-19f41b223996.png)

Here's the copy-paste version, if you're curious to play with it:
`گوربه تو گونی میکنن joined the group`

Here it does appear correct because the rest of the text is LTR.
