### ISSUE TITLE
[FEATURE REQUEST] Support zooming (Like TDesktop)

### ISSUE THREAD

**Issue by Muaath5** [UnigramDev/Unigram#2287]
Support Zooming (Scale interface) like TDektop In picture below:
![Scale interface in TDesktop](https://user-images.githubusercontent.com/60256639/111742486-55746f80-8899-11eb-9240-8ccb024e2f2c.png)

**Comment by MarcAnt01** [comment]
Hello, Unigram follows the system setting. If you change the system settings, the ui of Unigram will be made bigger/smaller according to that setting
![image](https://user-images.githubusercontent.com/43090263/111765318-81e1b900-88a4-11eb-9e67-d1c02b935701.png)

**Comment by Muaath5** [comment]
> 
> 
> Hello, Unigram follows the system setting. If you change the system settings, the ui of Unigram will be made bigger/smaller according to that setting
> ![image](https://user-images.githubusercontent.com/43090263/111765318-81e1b900-88a4-11eb-9e67-d1c02b935701.png)

I suggest add the ability without needing to change the system settings.
I don't want to change the system settings, Only Unigram.

I think this is the thing that let me didn't use Unigram mainly.

**Comment by FrayxRulez** [comment]
If every application on desktop had a similar feature I would say "you're right, all softwares offer this but Unigram".
Now, considering that's kind of the opposite (only Telegram Desktop offer this feature) and it's just because Telegram Desktop can't properly support screens with different DPIs I don't see a point for adding this feature. 

I will give you something to think about: all the softwares in your system use around the same metrics. This means that font size, buttons, icons, are all about the same. 
Now, if you feel the need to change Unigram scaling because it is too big/small for you, I can say for sure that the whole system appears too big/small, and not the single software.

If it's not the case, please, elaborate by explaining exactly what's the problem, maybe attaching some screenshots for comparison with the rest of the system (but not with Telegram Desktop where you're using a custom scaling)

**Comment by Tiberius1OOO** [comment]
> If every application on desktop had a similar feature I would say "you're right, all softwares offer this but Unigram".
> Now, considering that's kind of the opposite (only Telegram Desktop offer this feature) and it's just because Telegram Desktop can't properly support screens with different DPIs I don't see a point for adding this feature.
> 
> I will give you something to think about: all the softwares in your system use around the same metrics. This means that font size, buttons, icons, are all about the same.
> Now, if you feel the need to change Unigram scaling because it is too big/small for you, I can say for sure that the whole system appears too big/small, and not the single software.
> 
> If it's not the case, please, elaborate by explaining exactly what's the problem, maybe attaching some screenshots for comparison with the rest of the system (but not with Telegram Desktop where you're using a custom scaling)


i can actually ellaborate. 

Everything is fitting perfectly onto the screen  but unigram is just to small and too cumbersome to read. a lot of programs actually support custom sizing like Photoshop etc. 

The problem here lies with the system settings if you change it windows changes absolutly everything and most programs who do not support it or barely support it mees up every single layout. It is extremely cumbersome to set every single program up if you scale up the system scaling instead of just having those programs you need to use to be upscalable as a feature. 

I think there is nothing worse than using a unified upscale because every single program is extreme individual and 200% for one program like Unigram and 200% for like Photoshop would create extreme problems I do not need big buttons in photoshop I need a big workplace but that would be to small if I have everything upscaled by 2005 default. 

You see the problem? having a unified upscale is absolutly not the way to go.

**Comment by FrayxRulez** [comment]
Random screenshot from some random softwares open on my PC.
They all use the same font sizes, 12px and 14px.

![image](https://user-images.githubusercontent.com/8152849/116861938-3e4ccf80-ac04-11eb-9fe4-0495ad76361f.png)

**Comment by Tiberius1OOO** [comment]
You obviously don`t get the problem..

the problem is not EVERY software need sto be upscaled!

I do not need my Visual Studio to be upscaled because I know everything out of my head and I need a big space for my code that I can read fine when I am wearing glasses.

I also do not need to have big ass buttons on photoshop i need a big editing area that I can work one since I know that teh 12px font is cut and not copy

but if I want to normaly use my pc or my grandma or my father they do not wear glasses all the time because it hurst underneath a headset or is umcomftable for the eyes. That is why telegram needs upscaling so you can circumvent the eye strain and do not mees up 200% of your working programs

**Comment by MarcAnt01** [comment]
Sorry, but the "problem" is very specific. You can simply tell them to increase the system size, no messaging apps apart from Telegram Desktop have such option, so we are sorry but this won't be addressed

**Comment by FrayxRulez** [comment]
Apart from that implementing this would require weeks+ of work to likely achieve some mediocre result. All of this for an option that is available in some programs just because of backward compatibility (as old Windows versions don't have display scaling settings)

**Comment by Tiberius1OOO** [comment]
> Sorry, but the "problem" is very specific. You can simply tell them to increase the system size, no messaging apps apart from Telegram Desktop have such option, so we are sorry but this won't be addressed

Thanks for the reply. I can understand that. I have actually found a way to circumvent it by simply telling Unigram that Windows has the 150% with an app manifest file. it is not the best solution and i need to redo it every single time but it is better than having 0 workspace because as soon as I scale up windows all my windows are so big that I can barely ready anything inside of it and unigram saddly dose not scale well even with the system setting. (The names remain extremely small)


Would it be possible to at least change the name size and as well when I make the textsize bigger? and maybe get a bit more on the slider just like 2 sizes would be perfect.

**Comment by estheticode** [comment]
this is the only reason why i don't want to switch to unigram even though i like other features, the UI is just too small.

**Comment by FrayxRulez** [comment]
> this is the only reason why i don't want to switch to unigram even though i like other features, the UI is just too small.

Scale your system.

**Comment by MarsVertigo** [comment]
> > this is the only reason why i don't want to switch to unigram even though i like other features, the UI is just too small.
> 
> Scale your system.

This is pretty lazy on your part. I don't know how you still cannot understand how much pain this unwillingness to allow separate scaling cause. Bettergram and TG has this implemented. 

You only allow for chat text to be resized, which creates a weird hybrid environment. I really don't need scaling of my icons and texts elsewhere as otherwise everything else is fine. But my chat app needs to be scaled the way I require it, so this laziness and refusal of acceptance of the annoyance of such option is beyond me. 

Also, what is it with these fixed emoji palette tab by default which cannot be pulled back? Can you please reinstall Bgram and look how things are done UI wise and stop annoying users by pushing settings down their throat which should definitely be optionable? Thank you

**Comment by focushover** [comment]
For everyone saying to people to adjust their system wide ui scale, they are not considering specific user needs, inclusive design and accessibility recommendations.

Also people with any level vision impairment or special needs, as myself, even in a very low level, want the possibility to customize and make usage more comfortable. I felt very frustrated reading the comments, as so much energy needed to be spent trying to prove a point and request empathy. Instead, I am getting: "scale your ui".

I am comfortable with my windows ui at 100%, but yes, Unigram ui is VERY uncomfortable (for me) to read at 100%. I was able to resize text, but not general app ui.

Most apps offer ui scaling that is independent of the system settings. Scaling is offered via settings or Ctrl + key bind. Some examples:

- spotify
- discord
- slack
- telegram
- figma

This is a feature request, with valid points. 
And I would like to ask for respect and empathy for the colleagues who are trying to prove their point.

**Comment by FrayxRulez** [comment]
@focushover but I mentioned so many times to request this feature to Microsoft. I can't override the app DPIs, while I can scale some stuff most of the rest would just behave in a weird way and would render incorrectly or not scaled at all. And this would still require weeks of coding and testing: it's just not worth! Softwares usually don't have control over the framework rendering engine, especially if both the framework and rendering engine are closed source.

**Comment by flamebergh** [comment]
It's incredibly hard to read on a 2k monitor without this option, the reason why I stay on telegram desktop

**Comment by FrayxRulez** [comment]
@flamebergh https://support.microsoft.com/en-us/windows/make-text-and-apps-bigger-c3095a80-6edd-4779-9282-623c4d721d64

**Comment by nicola-sh** [comment]
The problem is urgent. I thought the developers had already added a local resizing of the UI after 3 years...

**Comment by nicola-sh** [comment]
> @flamebergh https://support.microsoft.com/en-us/windows/make-text-and-apps-bigger-c3095a80-6edd-4779-9282-623c4d721d64

This is not a solution to the problem.

**Comment by FrayxRulez** [comment]
A slider for changing UI scaling from 100 to 225% has been added to Settings > Appearance.

**Comment by muqtada-abdulrasool** [comment]
Hello, thanks so much for the implementation! It works like a charm!

Now, would it be possible, since this is now implemented, to set the GUI scale per-display 😅? My two displays are vastly different in DPI and resolution, so it would be a nice QoL feature!
