### ISSUE TITLE
Audio messages play in reverse order.

### ISSUE THREAD

**Issue by trypolis464** [UnigramDev/Unigram#2373]
## The problem
Something I've noticed is, voice messages play from the one you selected, to the most recent one. However, audio attachments play from the one you selected to the first one in the conversation. Is there a reason for this?
## How to reproduce:
Go into a conversation  with multiple voice messages and multiple audio files in it. Go to an older voice message, and play it. After that one plays, Unigram moves onto the voice message sent after that. Now, go click on an audio attachment, but make sure it has attachments before it. Once it plays, you'll notice it went to the file before itself.

Sorry if this is missing anything, first time issuer, and no template.

**Comment by makisukurisu** [comment]
![image](https://user-images.githubusercontent.com/49622129/118495613-08433b80-b72c-11eb-88e3-3e9e83a0e180.png)
There is a "shuffle" (actually reverse order) button in audio player interface so you can change it to whatever direction you want.

It's wrong labeled because... Looks like no reason from now on.
[String From TGAndroid](https://translations.telegram.org/en/search?lang_pack=android&query=Order)
