### ISSUE TITLE
tapping on a sticker-pack often jumps only to the first line of stickers

### ISSUE THREAD

**Issue by larsschellhas** [UnigramDev/Unigram#241]
I mean, when you open the sticker panel and tap on one sticker-pack often it doesn´t show stickers from that pack on the whole panel, but shows only the first line of stickers of that pack.
Because of that you have to scroll down to see more of the pack.

....sometimes it already shows the first line of the pack on the top of the panel, so that below you can see the other stickers from the pack.

**Comment by MarcelBrusius** [comment]
![wp_ss_20170331_0003](https://cloud.githubusercontent.com/assets/22997398/24565380/4f532fac-1655-11e7-8302-de44f08812bb.png)
Additionally, pressing on a sticker set for the first time since launch won't take you to the sticker pack. In the screenshot, I've actually pressed on the Simpsons  but am stuck on the recent stickers.
