### ISSUE TITLE
Proposal: Add Unigram to Winget package

### ISSUE THREAD

**Issue by lvinist** [UnigramDev/Unigram#2499]
as a windows 11 user i would really love to see unigram available on winget as it is easier way for me to install app

**Comment by SM-26** [comment]
with the MSstore update
you can do it now
![image](https://user-images.githubusercontent.com/39513660/135438116-2f3eb4cd-4ca4-43e3-b0ed-31498e941411.png)

**Comment by FrayxRulez** [comment]
I guess that this is no longer needed? 🤔

**Comment by MarcAnt01** [comment]
@FrayxRulez I think after the integration of MS store with Winget, it makes no sense to handle this on our own

**Comment by dada051** [comment]
I installed it a few years ago, via winget, and did'nt get any update. I just discovered that it's not updated. Maybe you should remove the winget entry if not updated regularly ?

**Comment by FrayxRulez** [comment]
We didn't add the app to winget. I believe that it just fetches the app from the Microsoft Store.

**Comment by makisukurisu** [comment]
@FrayxRulez Actually there are two entries in winget.

There's one from MS Store, and the other one, that is used by default - published directly to winget. However the publisher (not Fela, just so we're clear) abandoned the upkeep (apparently, since it's not updated), and didn't remove it from winget => people that used winget to install Unigram are stuck on an old version of the app.

```ps1
PS C:\Users\John> winget search Unigram
Name                           Id               Version     Source
--------------------------------------------------------------------
Telegram for Windows (Unigram) 9N97ZCKPD60Q     Unknown     msstore
Unigram                        Telegram.Unigram 10.8.0.9930 winget
```

@FrayxRulez, can't you request the removal of the package, given you have solid grounds for this request? (i.e - to remove potential confusion for CLI users)
