### ISSUE TITLE
The application cannot be installed

### ISSUE THREAD

**Issue by xiaowenlv** [UnigramDev/Unigram#2517]
Unigram-telegram for Windows 10 failed to be installed. The application installer cannot install the application package. Please ask the developer for the application package.

**Comment by makisukurisu** [comment]
@xiaowenlv https://t.me/unigramappx/94?single

You have to install these first. Try installing only xaml.2.6 first

**Comment by xiaowenlv** [comment]
Thank you. The installation is successful. Where can I check the shortcut keys? I am using Microsoft input method, but the screen reader cannot read the input. How can I solve the problem?

**Comment by makisukurisu** [comment]
@xiaowenlv I'm glad you managed to install it.

https://github.com/makisukurisu/Unigram/blob/develop/Documentation/Shortcuts.md

As for now you can go via link above to get shortcuts for Unigram.
Also there is NVDA add-on for Unigram. (It extends list of shortcuts)

https://t.me/unigramPlus

If I'm not mistaken it is in a channel above.

If your problem is solved you can close this issue.
