### ISSUE TITLE
Allow increasing UI font-size for users with visual impairment

### ISSUE THREAD

**Issue by ronilaukkarinen** [UnigramDev/Unigram#2536]
There are couple of problems with current font size settings:

- The max setting right now is not sufficient for people with visual impairment, max needs to be from 200% all the way to 400%
- The font size change is not affecting all sizes relatively, it should affect also: 
  1. Quoted text
  2. Link texts
  3. Text input (where you are writing your message) is very important to be larger and based on the font-size settings you choose, now it's not affecting there properly
  4. Other UI element texts

At the moment the app is unusable for people with Usher syndrome who need 300% font size. Tested with real people.

![Screen-Shot-2021-10-05-11-41-15 50](https://user-images.githubusercontent.com/1534150/135990461-cfa2078d-298a-4c3b-88a9-9b90396fbca2.png)

**Comment by makisukurisu** [comment]
It's not really recommended to adjust scaling inside Ungiram. Best way to get your text larger or smaller is to use Windows Scaling. And if you need text to be 300% default size in one app, you probably need it to be everywhere. That's why you'd like to go to Settings->Display->Advanced scaling settings->Custom scaling and set it to whatever value you need. Log out, log in and voila - you got large text everywhere including Unigram ofc.
![image](https://user-images.githubusercontent.com/49622129/135995334-02283147-6674-4e6d-a735-fd42ca98af67.png)

IMO setting dock to autohide is preferable with such settings, or use of larger/higher screens is advised, but I'm not going to go deep with this.

**Comment by ronilaukkarinen** [comment]
That is not really a solution. Not all apps scale correctly with full-on Windows scaling. The best way to provide accessibility is via inclusivity, allow user to choose per-app basis. Good apps support extra UI scaling like with Ctrl++ and Ctrl+- key shortcuts (or better yet an actual option in Preferences) rather than rely on the OS setting. Thanks.

**Comment by ronilaukkarinen** [comment]
Also why it's not a solution (sorry for double comment): You have to scale Windows like hell to get a decent font sizes in Unigram, then the other apps are like 500%. Sacrifice usability for the whole system for just one app? Nope. Fix your fonts. Thanks.

**Comment by FrayxRulez** [comment]
Allowing you to choose isn't something straightforward. It's actually an overkill from the technical point of view, considering that the system can do exactly the same with no changes required on our side.

**Comment by FrayxRulez** [comment]
A slider for changing UI scaling from 100 to 225% has been added to Settings > Appearance.
