### ISSUE TITLE
vey very small gui size on 1920x1080

### ISSUE THREAD

**Issue by gmankab** [UnigramDev/Unigram#2548]
If you look at the screenshots in readme.md than you can see normal gui size:
![image](https://user-images.githubusercontent.com/73340745/137796647-cd7809a5-679d-4118-ad77-05137d5fef48.png)
but this screenshot has 1024x768 resolution. If you look at 1920x1080 screenshot, it shows a very small interface:
![Без имени-1](https://user-images.githubusercontent.com/73340745/137797405-f4612a84-90d1-4905-bca0-b68f30e421ab.jpg)
It shows small text, small buttons and small icons.

Changing the DPI scaling in Windows' graphical settings is not a solution, because then Unigram became normal gui sized, but ALL other windows apps became very very big. To solve this bug you must add gui scaling in Unigram settings, no other way. Thank you.

 - Unigram: [8.1.6659 x64]
 - Windows: [11 21H2]

**Comment by MarsVertigo** [comment]
Guys, please listen to the above, this is soo incredibly lazy on your side not allowing such a basic, yet important functionality. It does not make even makes sense not to have it other than frustration.

**Comment by FrayxRulez** [comment]
> Guys, please listen to the above, this is soo incredibly lazy on your side not allowing such a basic, yet important functionality. It does not make even makes sense not to have it other than frustration.

What you define as something basic it's something that's supposed by most of the software out there, including all the ones installed on my computer. It's something that apps are not supposed to handle, in fact you can't really override this value.
I could scale the software manually, but then everything relying on the current DPIs (graphics, rendering in general, video player, etc etc etc) would just behave improperly.

**Comment by MarsVertigo** [comment]
Interesting, yet all my desktop com apps have it - be it Discord or vanilla TG, Bettergram and also Kotatogram, etc. What is a point of delivering product that lets you scale actual chat text but leaves everything else out. It is a pain for eyes nothing else. Not every software needs it, but communication which is specifically tricky for eyes should. Luckily, your Unigram is just one of few TG clones and I have since found an alternative. 

So yeah, let us know when you implement this functionality and also stop forcing users to have permanently opened emoji window and centered chat, etc.. More customization options less restrictions in general.

**Comment by FrayxRulez** [comment]
> permanently opened emoji window and centered chat, etc..

This is all stuff that you can disable.
You managed to mention three softwares that are actually the same software and one that's a website btw.

**Comment by FrayxRulez** [comment]
Anyway, you should refer to Microsoft for this, not to me, I've already explained that apart from the nonsense there's a technical limitation here.

**Comment by FrayxRulez** [comment]
A slider for changing UI scaling from 100 to 225% has been added to Settings > Appearance.
