### ISSUE TITLE
Locks up while typing messages

### ISSUE THREAD

**Issue by bstone108** [UnigramDev/Unigram#2630]
This problem appears to happen on every platform, but is most common on arm based windows 10 machines.

Symptoms.  when typing and the text box expands or wraps to accept a new line, the interface will stop responding, but the app itself hasn't completely frozen.  You can still type a message and press enter and it'll send, but the interface never updates again until the app is restarted.  The bug also happens occasionally when resizing the window.  This problem has existed since july and has gotten better or worse with each update, but never fully resolved and still persists today.  I have reported this bug in the past but believed it was related to the startup bug others were experiencing, however it doesn't appear so.

Again the problem is less of an issue on x86 based platforms but still happens there on a rare occasion, it's far more common on arm. I get no error messages of any sort when it happens, the interface just simply stops drawing updates on the screen, effectively frozen, even though everything still seems to be working in the background,  I can still hear messages arriving, still get notifications, and can still send, just can't see whatever I'm typing or doing or read new messages as the interface has stopped updating.  These problems started with the big interface update release around july of last year.

**Version Info**
 - Unigram: 8.4 6853 arm64 x86 x86-64, problem exists on all to various degrees
 - Windows: windows 10 21h2 and windows 11.  more frequent on windows 10 but also happens on 11 sometimes

I believe, since the problem mostly happens when the text box resizes to handle typed messages beyond one line, and that it started after the big interface update,  that the bug is most likely related to how the text input box is being rendered.  I'm willing to try any steps or idea's you have to try and further diagnose the cause or debug it. just give me some brief instructions on what you need.

**Comment by FrayxRulez** [comment]
> that the bug is most likely related to how the text input box is being rendered

If that's the case, there's nothing that I can do as I have no control over how Windows renders text.

> This problem has existed since july and has gotten better or worse with each update, but never fully resolved and still persists today.

I believe that this is just placebo, as the text field code rarely changes, and I never looked into this issue (as you're the only one who reported it so far, and I never experienced the bug myself)

**Comment by bstone108** [comment]
I don’t know why you are using the word placebo but it has no bearing on this.  I really have had this problem that length of time and reported it previously in a thread that I thought was the issue but turns out that wasn’t it. Again,  I’m just guessing as to the cause,  but it started when the interface was changed a little back in July.  I don’t know what aspect of the interface is causing this bug but it happens on every computer I own. I am more than happy to try and debug this problem myself,  mind sending me some instructions to get a debug/development build setup where I can get you info on where in the code the interface seems to be freezing up at?  Instead of brushing me off,  why not try letting me help?  I’m just not sure where to begin with windows apps as I’ve never really done any windows development before. Sent from Mail for Windows From: Fela AmeghinoSent: Saturday, February 12, 2022 10:07 AMTo: UnigramDev/UnigramCc: bstone108; AuthorSubject: Re: [UnigramDev/Unigram] Locks up while typing messages (Issue #2630) that the bug is most likely related to how the text input box is being renderedIf that's the case, there's nothing that I can do as I have no control over how Windows renders text.This problem has existed since july and has gotten better or worse with each update, but never fully resolved and still persists today.I believe that this is just placebo, as the text field code rarely changes, and I never looked into this issue (as you're the only one who reported it so far, and I never experienced the bug myself)—Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by makisukurisu** [comment]
You can find build instructions in Documentation folder. But it's really hard. Also - please, don't use formatting and remove all the text in email before typing in reply from mail. Because right now there is a bunch of excessive stuff and stylesheets.

Also my thoughts on issue. Freeze of UI when pasting a big chunk of text may be due to thread blocking or something like this, because whole UI stops rendering. (Just to let you know, this also does happen if you search for something in Files app, but, I cannot achieve same effect in Xbox app, Mail, Calendar (happens if you enter text to "contacts" field when creating a new event)
I played around more and found out that it's clearly dependent on how fast text is entered, so, the faster you enter the text (like pasting a large amount of text is almost instantaneous), the larger the odds of UI freezing for a bit. (side note, holding ctrl prohibits chat scroll, so move mouse up and down on chat list)

So it's hardware related too. I can, but don't want to underclock my laptop to test it out more precisely, but I guess that's the source of this issue: Windows or Unigram blocks rendering thread when drawing text, so the more blocks there are - the more likely it is that you will get dropped frames => freezing UI.

Just for enthusiasts with tweakers for CPU and displays out there - you can try to copy text of different length and see the results, then apply CPU frequency changes without changing text, then changing refresh rate (though this would require some sort of recorder to be able to cope with different refresh rates, and also would require looking at frame by frame sequences. Idea being - larger text => more dropped frames, larger CPU speed => lower dropped frames, higher refresh rate => dropped frames are more likely)

That's it. Sorry for such a long comment.

**Comment by Carighan** [comment]
I don't know whether this is the same issue, but I noticed that if I Alt+Tab into the window then type, nothing updates. All typing is registered, but it doesn't render.

But if I move my mouse (while it's on the window, though it doesn't matter whether it was on it before or not) then it instantly updates again. And if I move the mouse while typing (awkward, but just tried it) it will always show input immediately.

System is:
Microsoft Windows 11 Pro 10.0.22621.521
AMD Ryzen 5 3600
NVIDIA GeForce RTX 3070, driver version is 31.0.15.1748

**Comment by FrayxRulez** [comment]
Still?

**Comment by bstone108** [comment]
It’s never been fully resolved.  It gets better or worse from version to version but usually happens less often lately.  Course I swapped to a Mac as my primary machine and also use matrix primarily so I don’t use it as much anymore.  On Nov 8, 2023, at 5:53 AM, Fela Ameghino ***@***.***> wrote:﻿
Still?

**Comment by Carighan** [comment]
> Still?

No longer happening for me, but I also swapped out virtually all my hardware and am on a clean reinstall now.
