### ISSUE TITLE
Setting to automatically disable tray icon in power saving mode

### ISSUE THREAD

**Issue by MarcAnt01** [UnigramDev/Unigram#2640]
As pointed out in https://github.com/UnigramDev/Unigram/issues/2625 the tray icon causes a lot of activity in the background, since the app is basically running. My feature request is a simple setting that disables this behavior when power saving mode is on. This would be great for laptops and tablets

**Comment by FrayxRulez** [comment]
I think that this setting doesn't make sense and it would be too complicated to implement in terms of UX.
The tray icon itself doesn't cause any activity in the background, as the process itself doesn't execute any code apart from the message pump.
If you're worried about battery saver, you just want to fully close the app instead of leaving it in the tray icon.
