### ISSUE TITLE
Unigram crashes on start

### ISSUE THREAD

**Issue by IngoBoe** [UnigramDev/Unigram#2645]
**Describe the bug**
Unigram starts, shows the empty window with logo and crashes.
When resetting or reinstalling the app, I can start it, but it won't show a QR code. Sign in with mobile number is possible.
After successful sign in the app crashes again.

Issue has been discussed here but bug report has been closed:
https://github.com/UnigramDev/Unigram/issues/2460

**To reproduce**
Start Unigram. Will crash every time.

**Expected behavior**
Normal program start.

**Version Info**
 - Unigram: 8.5.6920.0 installed from Store
 - Windows: Windows 11 22000.434 ARM64

**Additional context**
Even though the system is ARM64 the x64 version seems to be installed. Installation path shows
C:\Program Files\WindowsApps\38833FF26BA1D.UnigramPreview_8.5.6920.0_x64__g9c9v27vpyspw\Unigram.exe.

I did not intentionally install a preview. This was the normal install from Microsoft Store.

**Comment by makisukurisu** [comment]
@IngoBoe Preview is just a name, it should be as it is.

To see installed arch tho, you can use Get-AppxPackage, it will show information about package. (there are parameters to filter packages, I'll update it a bit later if you won't find them) You either have neutral, ARM or Windows 11 is making arm from x86.

**Comment by IngoBoe** [comment]
Get-AppxPackage *Unigram*

RunspaceId             : d6e25c32-c3c6-4668-adf1-90ca69cdbed3
Name                   : 38833FF26BA1D.UnigramPreview
Publisher              : CN=D89C87B4-2758-402A-8F40-3571D00882AB
PublisherId            : g9c9v27vpyspw
Architecture           : **X64**
ResourceId             :
Version                : 8.5.6920.0
PackageFamilyName      : 38833FF26BA1D.UnigramPreview_g9c9v27vpyspw
PackageFullName        : 38833FF26BA1D.UnigramPreview_8.5.6920.0_x64__g9c9v27vpyspw
InstallLocation        : C:\Program Files\WindowsApps\38833FF26BA1D.UnigramPreview_8.5.6920.0_x64__g9c9v27vpyspw
IsFramework            : False
PackageUserInformation : {}
IsResourcePackage      : False
IsBundle               : False
IsDevelopmentMode      : False
NonRemovable           : False
Dependencies           : {Microsoft.UI.Xaml.2.7_7.2109.13004.0_x64__8wekyb3d8bbwe,
                         Microsoft.NET.Native.Framework.2.2_2.2.29512.0_x64__8wekyb3d8bbwe,
                         Microsoft.NET.Native.Runtime.2.2_2.2.28604.0_x64__8wekyb3d8bbwe,
                         Microsoft.VCLibs.140.00_14.0.30704.0_x64__8wekyb3d8bbwe…}
IsPartiallyStaged      : False
SignatureKind          : Store
Status                 : Ok

**Comment by IngoBoe** [comment]
I have a second machine here running Windows 10 ARM64. On this machine, I see the following Unigram version:
8.4.6853.0 *Arm64*. The store says, that there are no available updates. This version is working. 

So somehow on Windows 11 ARM64 the x64 version is installed in a newer build.

**Comment by OneCrazyRussian** [comment]
Also updated to 
Version           : 8.5.6920.0
Also started to have similar issue on Win10 x64, 
Unigram starts, I can open a chat, it works normally for a few seconds, then crashes (varying time, from instant to a few seconds)
If I dont open a chat it's fine.

Tried clearing data - works for a few seconds then starts again

Now the crash is not due to the new Video Stickers implementation - but rather seems to be caused by the AV codec coming with it
Event log data shows errors 1001 and 1000 including mention of avcodec-58.dll:
`Контейнер ошибки 1575614155979011630, тип 5
Имя события: MoAppCrash
Отклик: Нет данных
Идентификатор CAB: 0

Сигнатура проблемы:
P1: 38833FF26BA1D.UnigramPreview_8.5.6920.0_x64__g9c9v27vpyspw
P2: praid:App
P3: 1.0.0.0
P4: 61f93673
P5: avcodec-58.dll
P6: 0.0.0.0
P7: 61f8262e
P8: c0000005
P9: 00000000002044c0
P10: `

`Имя сбойного приложения: Unigram.exe, версия: 1.0.0.0, метка времени: 0x61f93673
Имя сбойного модуля: KERNELBASE.dll, версия: 10.0.19041.1466, метка времени: 0xe01c7650
Код исключения: 0x00001007
Смещение ошибки: 0x000000000010b362
Идентификатор сбойного процесса: 0x2f00
Время запуска сбойного приложения: 0x01d81b7ee3e5f53a
Путь сбойного приложения: C:\Program Files\WindowsApps\38833FF26BA1D.UnigramPreview_8.5.6920.0_x64__g9c9v27vpyspw\Unigram.exe
Путь сбойного модуля: C:\Windows\System32\KERNELBASE.dll
Идентификатор отчета: 078bf27b-c9fd-4084-9912-8c8aa873531d
Полное имя сбойного пакета: 38833FF26BA1D.UnigramPreview_8.5.6920.0_x64__g9c9v27vpyspw
Код приложения, связанного со сбойным пакетом: App`

Sorry the logs are in Russian, but still the cause seems to be this, as it did not happen before last update

**Comment by makisukurisu** [comment]
@OneCrazyRussian Can you send crash dump to Fela? If you don't have it in %CrashDump%, I'll send you reg file to enable crash dumps and will ask you to reproduce the crash.

**Comment by OneCrazyRussian** [comment]
> @OneCrazyRussian Can you send crash dump to Fela? If you don't have it in %CrashDump%, I'll send you reg file to enable crash dumps and will ask you to reproduce the crash.

Aaand now that I set crash dump collection up I can't reproduce it after reboot. If it acts up again I'll send it in,

**Comment by IngoBoe** [comment]
> Also updated to Version : 8.5.6920.0 Also started to have similar issue on Win10 x64, Unigram starts, I can open a chat, it works normally for a few seconds, then crashes (varying time, from instant to a few seconds) If I dont open a chat it's fine.

Looks like a different issue. Unigram does not start here and I can't open any chat. 
Also the crash is not related to a codec here.

**Comment by Alovchin91** [comment]
The guy is pretty clear he doesn't care about ARM64 users, he considers us an annoying minority. Every Unigram release is a gamble: it randomly drops ARM64 version. Just use Telegram Desktop, Unigram is not for us.

**Comment by FrayxRulez** [comment]
@Alovchin91 It’s true, please disperse

**Comment by FrayxRulez** [comment]
@Alovchin91 But it’s also because adding x86 and ARM64 increases the build time by an hour or so, and it often requires many patches and so. I’m not sure that this is worth when we’re talking about less than 0,1% of users, especially as they can use x64 without any hassle, or they can build Unigram themselves if they want the latest shiny ARM64 version. I kindly ask you not to judge without knowing the background. Thanks!

**Comment by FrayxRulez** [comment]
@Alovchin91 (Also, I’m not aware of Telegram Desktop having any ARM64 release on Windows?)

**Comment by Alovchin91** [comment]
> especially as they can use x64 without any hassle

Apparently they cannot, otherwise there wouldn't be this issue.

> I kindly ask you not to judge without knowing the background.

I don't want to judge you but I'd like to ask you to be crystal clear that you don't want to support ARM64. Maybe put it in the README, because it's not what people expect from a UWP app.

> (Also, I’m not aware of Telegram Desktop having any ARM64 release on Windows?)

They don't, but maybe it runs better in x64 emulation, idk.

**Comment by FrayxRulez** [comment]
@Alovchin91 I would say that out of 273 updates that Unigram received through the Microsoft Store at least 250 had ARM64 support as well.

**Comment by FrayxRulez** [comment]
@Alovchin91 I’m not the only one to compile Unigram and unfortunately the other person taking care of this is not able to take care of ARM64 because he needs to keep compiler compatibility for the rest of the Telegram stuff that he needs to build. When this happens ARM64 can’t be released for obvious reasons.

**Comment by MarcAnt01** [comment]
@Alovchin91 how can Telegram Desktop run better if Unigram crashes, like what are you comparing it to?

**Comment by Alovchin91** [comment]
> how can Telegram Desktop run better if Unigram crashes, like what are you comparing it to?

I'm comparing it to the original post; I could login to Telegram Desktop right now just fine.

**Comment by FrayxRulez** [comment]
@MarcAnt01 Can you please avoid off topic and flames? Thanks.

**Comment by Alovchin91** [comment]
@FrayxRulez It looks like every time there's no ARM64 version, Unigram starts crashing for some users under x64 emulation. I understand your reasoning behind not having an ARM64 version at all, but that gamble from release to release is annoying, especially for those users who rely on it.

**Comment by Alovchin91** [comment]
> he needs to keep compiler compatibility for the rest of the Telegram stuff that he needs to build

Is there any reason why you don't use GitHub Actions to build releases? 🤔

**Comment by MarcAnt01** [comment]
You are literally, the one who said "please disperse" to a user, so think about your sentences before criticizing a simple question by someone else, especially since I was only asking for a clarification on that point

**Comment by FrayxRulez** [comment]
@Alovchin91 Unfortunately at the moment there’s no way around it, as Microsoft Store promotes x64 version of the app even though I always leave an ARM64 build of the app just in case. 
We can’t use GitHub actions because Unigram is a complex project and it requires different dependencies that aren’t easily buildable by GitHub actions, by example the heavy patched version of WebRTC that we use that is 15gb just to be cloned from chrome repositories, or TDLib that comes as a Visual Studio Extension (and VSIXs can’t be installed in shared build servers)

**Comment by Alovchin91** [comment]
@MarcAnt01 Fela is not the nicest person (especially since his "Insiders" channel is open and Google Translate is available 😉) but let's be respectful to him/them for making Unigram happen at all ☺️

My point is, please decide whether you support ARM64 or not. If you need help, you can always request it from the community. I for one would have been happy to share a Snapdragon Developer Kit with you as a build machine, if I could buy it here in the Netherlands ¯\\\_(ツ)\_/¯

**Comment by FrayxRulez** [comment]
The app is available again on ARM64 🥳

**Comment by IngoBoe** [comment]
Thank you!
