### ISSUE TITLE
video "open in" function has no effect

### ISSUE THREAD

**Issue by YoYspoon** [UnigramDev/Unigram#2647]
Worked once for me and I streamed media to potplayer then forgot what I did and it stopped doing anything at all. Tried re-install and it didn't work

**Comment by makisukurisu** [comment]
Most likely because you still have it assigned as default one, but it points to wrong executable, or a windows bug.

![image](https://user-images.githubusercontent.com/49622129/154110757-f4377bf8-6d33-4392-a56e-8af8ec498032.png)
You should get this thing (at least), you can try removing default app for video formats.
