### ISSUE TITLE
Auto start but minimized to notification tray?

### ISSUE THREAD

**Issue by frnmz** [UnigramDev/Unigram#2689]
Hi, thanks for the great app!
But I think it's good to have an option to auto start unigram but it's minimized to notification tray.
Just like regular telegram app.

The current unigram behavior when autostart is enabled is the app will minimized to taskbar, not to tray.

**Comment by carlosmg2** [comment]
same here. Have just installed Unigram and it's the only annoying thing.
Please add autostart minimized to tray.

**Comment by Pro-cyber-byte** [comment]
Yeah , this is really the only thing that's keeping me from completely switching to Unigram .. please add this feature , it's a big annoyance that the official telegram client handles better ..

**Comment by FrayxRulez** [comment]
As someone opened this on bugs.telegram.org, I'm closing here.

**Comment by palopezv** [comment]
@FrayxRulez  I'm necrobumping this bug report as Telegram UWP was dropped by upstream. Any chance of implementing in Un igram?

**Comment by FrayxRulez** [comment]
Unigram is not a fork so there’s no “upstream”. Telegram Desktop has never been a UWP app, while Unigram was and still is.

**Comment by palopezv** [comment]
@FrayxRulez Hmmm. Let's get some things straight.

- Telegram did have a hybrid app in the store until some two, three years back; probably Windows 10 only. Same problem, no systray minimization at start.

- Last time I checked, telegram.org is TLDB's upstream.

- Unigram design is a faithful UX copy of the C++ app therefore without examining the source code, it is easy to presume you are using parts of upstream's middle layer to reproduce the UI and UX on top of TLDB.

All in all, your answer comes across as acrimonious instead of terse and it is not polite. My apologies if I pushed the wrong button.
