### ISSUE TITLE
folder doesn't load

### ISSUE THREAD

**Issue by k-kruglov** [UnigramDev/Unigram#2703]
**Describe the bug**
One (last) of the four folders doesn't display its chats

**To Reproduce**
1. I have 4 folders, Люди, Unread, cm/gamedev, каналъ
2. I installed Unigram and logged in via QR code and password
3. At first, two last folders didn't load - cm/gamedev and "каналъ"
4. I've restarted the app a few times and cm/gamedev began to display
5. Last folder doesn't load still, no idea what to do about it
6. No other folders load after I click last bugged folder.

**Expected behavior**
folder loads fine

**Screenshots**
https://imgur.com/a/ruLPwoe

**Version Info**
 - Unigram: 8.6 (7182) x64
 - Windows 11: 22000.593

**Additional context**

**Comment by k-kruglov** [comment]
upd: reinstall didn't help
but, what helped is to "edit folder" - didn't change anything - "save", folder loads after that.

**Comment by FrayxRulez** [comment]
Generally speaking reinstalling never helps.
What happened here is that in the folder you added some chat (likely a group/channel) that's no longer accessible, and because of this TDLib fails to load the chats.
By editing and saving the folder the app automatically filtered out the inaccessible chat, "fixing" the issue.

**Comment by FrayxRulez** [comment]
This has been patched by https://github.com/UnigramDev/Unigram/blob/develop/Unigram/Unigram/Services/ProtoService.ChatList.cs#L71,L78
Additionally, a similar solution will be included in TDLib 1.8.6.
