### ISSUE TITLE
Missing of the cursor in black & gray themes 

### ISSUE THREAD

**Issue by TurboPlanner** [UnigramDev/Unigram#2717]
**Describe the bug**
If you switch to black or gray themes of Unigram then after some time the editing cursor disappeared.
See the screenshot. I'm typing the text and cursor is invisible. 
Previously I think that the cursor switched to black color after some time. However I see same bug with gray theme.

**Expected behavior**
Return editing cursor, pls :)

**To Reproduce**
The bug has unstable repro. You need to use Unigram about 10-15 minutes. After it you will see that the cursor disappeared.
I updated Unigram to all last releases. All previous 5 builds have same bug. 
If I restart the Unigram then the cursor is visible again... for 10-15 minutes before disappeared again.  

I think that you can catch this bug if you switch in black or gray theme and work with Unigram 1-2 days.

**Version Info**

Version of Unigram - 8.7 (7352) I have auto update to new version

OS
Edition Windows 10 Enterprise
Version 21H1
OS build 19043.1586
Experience Windows Feature Experience Pack 120.2212.4170.0
Updated to last cumulative fixes

![cursor_bug](https://user-images.githubusercontent.com/92896692/164909132-eb715cbe-f53e-4cdf-84f2-0e5c907d371b.jpg)

**Comment by MarcAnt01** [comment]
Hello, thanks for reporting this bug, but why did you delete every field of the template on purpose? This information is really important to track the bug, please create a new ticket filling every field

**Comment by TurboPlanner** [comment]
If you about version and OS then I would like to inform you that I don't see this fields.
 
Version of Unigram - 8.7 (7352)   I have auto update to new version

OS 
Edition	Windows 10 Enterprise
Version	21H1
OS build	19043.1586
Experience	Windows Feature Experience Pack 120.2212.4170.0
Updated to last cumulative fixes

**Comment by MarcAnt01** [comment]
Thanks for providing the information, I am talking about the following field that clearly appear once you open a ticket:

**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Version Info**
 - Unigram: [e.g. 7.8.6339 x64]
 - Windows: [e.g. October 2018 update]

**Additional context**
Add any other context about the problem here.

**Comment by TurboPlanner** [comment]
I understood and I corrected the bug description in first message.

This bug may be complex to fix because it has unstable repro. Previously I contacted to Unigram developer. He asked me Unigram log. May be the log can help in this situation?

**Comment by MarcAnt01** [comment]
I think you are referring to TDLib logs, in this case they shouldn't be necessary

**Comment by FrayxRulez** [comment]
There's a bug in Windows, either UWP or the OLE component used for the RichEditBox, that causes the caret to disappear in certain conditions. Restarting the app solves the issue.
