### ISSUE TITLE
Unigram does not restore preview of people who reacted a message once "react" counter gets back from 4 to 3

### ISSUE THREAD

**Issue by Kenya-West** [UnigramDev/Unigram#2768]
**Describe the bug**
When you react to a message that already has been reacted by 3 people with the same reaction, the "reacted" counter is set from 3 to 4 and then lost previews. It is OK, it should be like this.
But when you un-react the same message, preview of reaction is not restored. 

**To Reproduce**
1. Find a message that has three people reacted with same reaction
2. Click to react with the same reaction
3. Click again to un-react
4. See that preview is not restored

**Expected behavior**
Preview of people who reacted should be restored,

**Screenshots**
Gifs are better:
| Official client (Android) | Unigram |
|:-------------------------:|:-------:|
| ![2022-06-26_18-26-11](https://user-images.githubusercontent.com/12271104/175807946-83339007-1030-4927-8215-2c244fa9d71e.gif) | ![2022-06-26_18-26-28](https://user-images.githubusercontent.com/12271104/175807953-89051477-bc01-472a-a55b-9580d59c441b.gif) |

**Version Info**
 - Unigram: 8.8 x64
 - Windows: 11 Pro x64

**Comment by FrayxRulez** [comment]
This will be improved on TDLib side.

**Comment by levlam** [comment]
I doubt that this can work in the expected way in any official client, if you relaunch the app/wait for up to a minute/reenter the chat and alllow the app to fetch actual reaction state from the server before removing the reaction. It accidentally works, because they don't properly update local state after adding the reaction, but TDLib does.
