### ISSUE TITLE
Automatic message translation

### ISSUE THREAD

**Issue by nuui** [UnigramDev/Unigram#2787]
Automatic translation of received messages
接收到消息自动翻译

**Comment by makisukurisu** [comment]
This is already possible.
Open Settings (in Unigram, click on profile picture in top left corner of the app), Language Settings, enable Show Translate Button.

Then - right click on a message and select Translate.

**Comment by makisukurisu** [comment]
Closing this issue. If you have any problems with it - feel free to comment.

**Comment by MavenDE** [comment]
I second this. Would be amazing to have automatic translation or a button to do so.

**Comment by MarcAnt01** [comment]
@slothic @MavenDE this isn't going to happen any time soon,  unless official clients implement this feature

**Comment by FrayxRulez** [comment]
@MarcAnt01 It’s not about that really, translations are just extremely expensive, it would be a huge waste of money to translate every single message

**Comment by Stele77** [comment]
I don't know how, but the "Nekogram" client on Android can do this, and has several options like DeepL, Google, Yandex, Microsoft, Lingocloud, YouDao, Baidu, Sogou.
Since that project is also hosted on Github, it should be possible to check their solution. It is a FOSS project, and they don't charge money for it, so there should be a way.
Auto Translation is really the make-or-break feature for me, but also for many others. If you are following any channels of languages, you don't know well or at all, it is just not doable to click translate every single message. Sounds harsh, but as it is now the feature is basically useless for real world, daily use.
I blog about the war in Ukraine, and this single feature could help so many people, reporters, bloggers but also regular citizens to study the sources directly. It would be a godsend.
Thanks in any case for your work!

**Comment by kntjsprr** [comment]
> I don't know how, but the "Nekogram" client on Android can do this, and has several options like DeepL, Google, Yandex, Microsoft, Lingocloud, YouDao, Baidu, Sogou. Since that project is also hosted on Github, it should be possible to check their solution. It is a FOSS project, and they don't charge money for it, so there should be a way. Auto Translation is really the make-or-break feature for me, but also for many others. If you are following any channels of languages, you don't know well or at all, it is just not doable to click translate every single message. Sounds harsh, but as it is now the feature is basically useless for real world, daily use. I blog about the war in Ukraine, and this single feature could help so many people, reporters, bloggers but also regular citizens to study the sources directly. It would be a godsend. Thanks in any case for your work!

+1  I'm having a similar use-case as well. I need this to be implemented if possible, using google translate api.
