### ISSUE TITLE
How to Backup Unigram

### ISSUE THREAD

**Issue by ksaltik** [UnigramDev/Unigram#2873]
Hi,

How can I backup unigram in windows to move it another computer both files and chat logs ( all groups etc)

Thanks for reply

**Comment by makisukurisu** [comment]
That's not really needed, since Telegram stores all your data in the cloud (except for Secret chats).

**Comment by amirmahdifard** [comment]
@makisukurisu i think his mean that he wants to backup his downloaded files and his logs and his account so he don't need to logging to his account anymore.

**Comment by FrayxRulez** [comment]
If you're using Unigram from the Store, this is the location where you can find all files generated by the app: `%LOCALAPPDATA%\Packages\38833FF26BA1D.UnigramPreview_g9c9v27vpyspw\LocalState`
Otherwise, the folder that you're looking for is the following: `%LOCALAPPDATA%\Packages\TelegramFZ-LLC.Unigram_1vfw5zm9jmzqy\LocalState`

**Comment by jsfrau** [comment]
Hello, tell me how to view the chats stored in the client? I used your application before, and it saved my chats at that time. Now there is a great need to access them. When I turn off the internet on the computer and open Unigram, I can read old chats and even search through messages. There are 3 files in the files:
db.sqlite
db.sqlite-shm
db.sqlite-wal
td.binlog

But they do not open with any SQLite data viewing applications. Please help, how can I read the remaining chats in the application?
