### ISSUE TITLE
UI overlaps when sending pictures to someone

### ISSUE THREAD

**Issue by MrFredber** [UnigramDev/Unigram#2905]
This is always happen until you switch the chat and go back to this chat

**To Reproduce**
1. Send an image to someone
2. This bug will shown
3. Go to other chat and go back to this chat
4. This bug will disappear 

**Version Info**
 - Unigram: 9.1 (7880) X64 Direct
 - Windows: 10 22H2 (19045.2251)

**Screenshot**
![image](https://user-images.githubusercontent.com/33953266/203354071-90bc4cc9-72d2-45f9-a4a0-8a80c39caa23.png)

**Comment by MarcAnt01** [comment]
Please, use template for reporting bugs.

If you are not going to recreate this one - please, provide details in a reply, or initial message (hit ... button, choose edit)
Things like Unigram version, Windows version, etc. are crucial for bug-fixing.

(You can copy-paste template and fill in the details from "New issue"=>"Bug Report", or create a new one using same template, otherwise the issue will be closed)

**Comment by MrFredber** [comment]
Sorry. I will add missing parts.

**To Reproduce**
Steps to reproduce the behavior:
1. Send an image to someone
2. This bug will shown
3. Go to other chat and go back to this chat
4. This bug will disappear 

**Version Info**
 - Unigram: 9.1 (7880) X64 Direct
 - Windows: 10 22H2 (19045.2251)
