### ISSUE TITLE
Instant view (maybe Unigram, overall) should use a web view for displaying HTML content

### ISSUE THREAD

**Issue by cdimauro** [UnigramDev/Unigram#2948]
Instant view works decently on some HTML contents but on some others (especially content grabbed from internet forums) the rendered page looks really ugly.

This is because it looks like that HTML elements are displayed as single UI widgets which take-up the full space horizontally. So, you end-up with some text which is displayed nicely, but if there's an image which just follows then it's displayed below the text, alone; and so with the following content.

An example can be found on this HTML content: https://telegra.ph/Master-Axe-6-comments-01-22
Opening it with the instant preview, it gives this:
![image](https://user-images.githubusercontent.com/4763177/213941701-d686485e-5148-4cce-a082-1c8671f0b197.png)

However downloading the content from the above URL (https://telegra.ph/Master-Axe-6-comments-01-22) and displaying it with the browser it'll give a much better rendering:
![image](https://user-images.githubusercontent.com/4763177/213941777-dc4a3fbb-b51d-4bd3-a194-193b3007be02.png)

**### Suggestion: instead of using a single UI widget for each HTML element to be displayed, it's much better to delegate the full HTML content rendering to a web view widget.**

**Comment by makisukurisu** [comment]
From what I can see in #2949 and from https://instantview.telegram.org/ - Telegram actually doesn't send HTML data in Instant View, but instead - it send some kind of JSON list of elements that are interpreted by clients.

So I guess - this behavior is intended.
_And to be honest - if you follow provided link - it looks pretty much the same in Unigram, but images are a slightly bigger in Unigram._

**Comment by makisukurisu** [comment]
![Screenshot_20230123-231304.png](https://user-images.githubusercontent.com/49622129/214151193-6a670021-a3b7-42cb-b7de-e752434312d2.png)

![Screenshot_20230123-231251.png](https://user-images.githubusercontent.com/49622129/214151192-14e8db61-7085-4d41-9f9f-550b618db3ff.png)

If only you didn't disable css for the webpage...

In this specific example (with Telegraph) - all images are actually centered.
And overall - thus is how Instant View works, it's completely intentional. (You may refer to official pages for Instant View, but, afaik - there's no "inline image" element, and all images should be centered by guidelines/design)

Arrow down is probably tightly related to accessibility, so, perhaps, it should stay as is.
(The same behavior is applicable to messages in chat, if I'm not mistaken, but perhaps it requires Narrator to see it more prominently)

Fela's word is final of course, I'm just throwing some material into discussion 🐢

**Comment by cdimauro** [comment]
> 
> If only you didn't disable css for the webpage...
I haven't: I just grabbed the content from Telegraph's link using Python's requests library (so, taking the raw content and dumping it to a file. Then opening it with the browser).
> In this specific example (with Telegraph) - all images are actually centered. And overall - thus is how Instant View works, it's completely intentional. (You may refer to official pages for Instant View, but, afaik - there's no "inline image" element, and all images should be centered by guidelines/design)

OK, if this is by IV's design then my request goes against it and it might be rejected.

I still think that it's an improvement for the end users, but guidelines are there to be respected.
> Arrow down is probably tightly related to accessibility, so, perhaps, it should stay as is. (The same behavior is applicable to messages in chat, if I'm not mistaken, but perhaps it requires Narrator to see it more prominently)

Yes, the same happens with messages. I think that it's how Unigram intrinsically works (it's a regular GUI desktop application, and those applications usually create UI widgets for every displayed object).

This has pros and cons. But, as a user and specifically for how Telegram works, I prefer to have a more "web-like" user experience for messages and IV contents (like Telegram's web version).
> 
> Fela's word is final of course, I'm just throwing some material into discussion 🐢

np. I'm just a user and I'm trying to give some contribute as well to have a better Telegram client, if possible. :)

**Comment by MarcAnt01** [comment]
Closing this since a custom way of visualizing iv is not planned
