### ISSUE TITLE
FPS capped to 60 fps?

### ISSUE THREAD

**Issue by zizhengwu** [UnigramDev/Unigram#2966]
Does Unigram have FPS capped to 60 fps? This makes the app less enjoyable to use on high refresh rate screens compared to the official Telegram for Windows

**Comment by zizhengwu** [comment]
..and the constant framerate drops are very noticeable, perhaps a duplicate of https://github.com/UnigramDev/Unigram/issues/2501

**Comment by FrayxRulez** [comment]
@zizhengwu Unigram uses the UI framework built-in and part of Windows and it has consequently no control over the refresh rate or frame rate. Stickers and GIFs are indeed capped to 60 fps, but this is because stickers and gifs with more than 60 fps are simply not supported by Telegram. 
I highly doubt that Telegram Desktop can do any better than 60 fps, as being it fully software rendered it can go much farther than there.

**Comment by zizhengwu** [comment]
Thank you @FrayxRulez! That's good to know.. I did notice the fps cap / flickering / framerate drop issue is very similar to some other UWP apps I have used. I'm not an expert in that space, perhaps it's some weird windows 11 bug. I am also using scale 200% if that matters.

**Comment by zizhengwu** [comment]
Also, not entirely sure, it may have something to do with nvidia g-sync, low latency mode, etc. I remember seeing UWP fps cap being cited as an issue (even for games) years ago.

**Comment by zizhengwu** [comment]
I toggled on/off a few different settings, but I can't get away with the fps cap / flickering / framerate drop. Maybe some other people can sort it out.

**Comment by makisukurisu** [comment]
I guess we can close this issue too?

There's no explicit limit, as I can see, except for stickers/emoji.

**Comment by zizhengwu** [comment]
The fps cap issue I had seemed to be gone. Not exactly sure what resolved the issue. My guess is that, with my gsync compatible display, the 3d settings in nvidia control panel should be
- vertical sync: ON
- low latency mode: ultra
