### ISSUE TITLE
Portable Version?

### ISSUE THREAD

**Issue by lepras** [UnigramDev/Unigram#2997]
I am not too sure how native microsoft apps work and there is [this](https://github.com/UnigramDev/Unigram/issues/955) related issue but if we can get a portable version it would be great, thx for all the efforts!!

**Comment by makisukurisu** [comment]
It is technically not possible to create a portable version of the app using the current framework (UWP).

Maybe this will change if Unigram migrates to WinUI.

As for multiple instances - I believe that nothing has changed this far, but from personal experience - (if there's no such option on right click on profile) you can at least open some chats of different users as separate windows.
Also - notifications do (or should?) work for both accounts at the same time.

**Comment by MarcAnt01** [comment]
Hello, even moving to WindowsAppSDK with WinUI 3, this would not work keeping the app packaged, so I think it can be closed.
As for multiple instances, they are possible in theory, but they haven't been considered actually, since Unigram comes with multiple account support and has the possibility of opening chats in new windows.

**Comment by FrayxRulez** [comment]
@MarcAnt01 I plan to support unpackaged distribution after moving to WinUI 3, but this won't happen before 6-12 months
