### ISSUE TITLE
Unaccessible topics in group for blind

### ISSUE THREAD

**Issue by AlexandrKozlovskiy** [UnigramDev/Unigram#3014]
Hello. I know,what this issue exists,but it did nothing to fix it,so i create it again,to have it in top. In unigram topics still unaccessible for screenreaders,i.e instead of topic names we have json information. Unigram most accessible client for windows,but this and some other problems ignore for a now. Whether it difficult to fix several lines of code and fix issue? Because unigram update and it,in my opinion,more difficult to create a new version,than fix this or similar issues. Yes,i know,what some accessibility issues not so easier to fix,but,in my opinion,not this or similar issues. Please not close this issue,while it will not be fix. Thanks.

**Comment by MarcAnt01** [comment]
@AlexandrKozlovskiy Hi, we are sorry but this is not how the GitHub issues are meant to work.
The details of your previous issue were moved to https://github.com/UnigramDev/Unigram/issues/2953 tracking all the issues about topics. As you can see the issue is still open, since the majority of the problems haven't been addressed. If you want to know when your problem gets solved you can subscribe to that issue, we cannot keep this open
