### ISSUE TITLE
Keyboard sometimes doesn't show after clicking on stickers icon

### ISSUE THREAD

**Issue by bugada** [UnigramDev/Unigram#319]
Go in a chat, press the stickers icon on the message bar, the stickers panel shows up; then press in the text input and the keyboard shows up;  press again the stickers icon, nothing happens, if you repress that icon the stickers shows up but then clicking in the text input won't show the windows keyboard.

Unigram 0.3.442.0
Windows version: 10.0.15063.414

**Comment by FrayxRulez** [comment]
Is this still here?

**Comment by bugada** [comment]
Yes still here, using latest store version

**Comment by larsschellhas** [comment]
In the current native build, the keyboard always show up, when clicking in the text field.

But if the sticker flyout it open and i click on the textfield, the sticker flyout will not Close. It will just be hidden behind the upcoming Keyboard. Because of that a douple tap on the Stickers button is needed to get back to the Stickers.

**Comment by bugada** [comment]
I can't reproduce it anymore nor in develop branch nor in in native branch.

**Comment by bugada** [comment]
Correction: Larsschellhas issue is reproductable on native, I'll take a look.

**Comment by FrayxRulez** [comment]
There isn’t any difference between native and develop
