### ISSUE TITLE
Chat not leading you to the last received message with new (Windows Store) update

### ISSUE THREAD

**Issue by Fernandus91** [UnigramDev/Unigram#322]
This is quite different from #175 e #192 (already closed) but, with the new app version when you enter a chat, it does not lead you to the last received message.

App version: 0.3.443.0 on Windows 10 mobile (14393.1358)

**Comment by bugada** [comment]
In my case it works well, but not for messages sent by bot keyboard

1) Open a chat with bot bot buttons present, the last message shown is correct
2) Press a button on the keyboard, the message sent is not displayed (is present bat the chat doesn't scroll down)
3) The response from server is not displayed (like point 2).

If you scroll down the chat to show the two new messages, then the following behavior is correct. So the problem is present only after the chat has been opened from the list.

**Comment by Fernandus91** [comment]
@bugada the behaviour is similar, but not the same. In my case it happens with every chat (bot included) everytime I select it: it is not showing the last message, which is hidden under the keyboard.

**Comment by bugada** [comment]
@Fernandus91 i can experience the problem even when there are unread messages: the last message i can i see is "Unread messages" and if you type something you loose the last message from the view.

**Comment by Fernandus91** [comment]
Oh ok, I misunderstood. Basically it is the same problem then, so it is confirmed 🙂

**Comment by larsschellhas** [comment]
it loads the last block of Messages.
actually, if you open the Chat twice without sending a message, it will open it at the last message at the second time.

I´m not sure, what or when we can do something about this. So it´s just for your Information. ;)

**Comment by Hachinamio** [comment]
I got this problem as well. Sometimes it will lead to the latest messages, sometimes the keyboard will cover the latest message.
