### ISSUE TITLE
First chat is shown after reopening

### ISSUE THREAD

**Issue by GeorgHoffmeyer** [UnigramDev/Unigram#332]
Even if I leave in the overview, the last chat is shown when I reopen the app.

**Comment by FrayxRulez** [comment]
Can't reproduce

**Comment by Fernandus91** [comment]
There is no a way to reproduce it. It is completely random, but in my case it often happens when i don't close the app, exiting only pressing the arrow

**Comment by GeorgHoffmeyer** [comment]
I have the impression it could have something to do with the unread message counter. If a chat is marked as unread, it pops in front on windows mobile.

**Comment by bugada** [comment]
I can reproduce it with 443 (store version) not with 506. What version are you using?

**Comment by DarthJahus** [comment]
I was experiencing this on older versions, but not any more, with `0.4.506.0`.

**Comment by GeorgHoffmeyer** [comment]
I use the latest from the store which is 0.3.443.0.

**Comment by FrayxRulez** [comment]
I habe to say that this issue is not solved in 0.4.506

**Comment by FrayxRulez** [comment]
Thanks to @DarthJahus for the repro:

1. Make sure Unigram is closed
2. Get a notification and tap on it, it opens Unigram in the correct chat
3. Return to conversation list (with back key / button)
4. Press home button
5. Launch Unigram from Start screen or App list
6. Unigram goes to the chat you opened via the notification instead of returning to previous state (chat list).
