### ISSUE TITLE
HTTP proxy support

### ISSUE THREAD

**Issue by simonsmh** [UnigramDev/Unigram#485]
If unigram has HTTP proxy and that would be way better.

**Comment by FrayxRulez** [comment]
Unigram doesn’t use HTTP at all to work, so it isn’t possible to use an HTTP proxy neither, sorry

**Comment by simonsmh** [comment]
But the desktop version supports http **proxy**...

**Comment by FrayxRulez** [comment]
That’s why you can use a SOCKS5 proxy

**Comment by davux** [comment]
This issue is real and shouldn't be ignored, please reopen...

HTTP proxies are real: in many corporate environments (if not all) there's an HTTP proxy. I can't use Unigram because it fails to connect, so I have to uninstall it. The official desktop client works fine, as it respects system-wide proxy configuration.
