### ISSUE TITLE
Export chats

### ISSUE THREAD

**Issue by alskdjfj** [UnigramDev/Unigram#541]
Now that unigram X can store all the chats in a local cache, it would be wonderful if we could export our conversations as a file (an xml file for example), with also all the pictures, videos, files, gifs just by selecting with a button which chats do you want to export. In the xml file, there could be info about:

- message content

- message time

- status of the message

This feature could be also active for secret chats.

**Comment by FrayxRulez** [comment]
Sorry but I'm closing this for now

**Comment by alskdjfj** [comment]
Can I ask you why? At least you could provide us a reasonable answer.

**Comment by alskdjfj** [comment]
No that I know. That is why I was asking for it since it is a very active project but it seems that every project related with telegram doesn't want to add this ability, which is quite strange...

**Comment by alighamari** [comment]
@alskdjfj Thats the point, this is a telegram side ability, ask them in twitter for this.
Also telegram is a fully cloud based messenger why you need that? In WhatsApp may you need them but not in telegram

**Comment by alskdjfj** [comment]
Excuse me but, you are totally wrong. 

1) if you have the ability to store and get the text from the storage to show it, that is to fill an itemlist, I don't understand why you couldn't write it in an xml file. It is not as difficult and to me it is an issue that has to be covered by the coders of any Telegram project and since all data has been storages it is no more a problem of that "official coders don't allow you to do this" (at least from a coding side). The official program won't do it as said several times by their developers. So it is a matter of other unofficial Telegram projects.
2) Telegram doesn't need to be fully cloud messenger. Secret chats aren't stored in telegram servers (supposedly).
3) I will be always owner of my work and so on, I must have the tools to be owner.  If I want to keep tracked my conversations in external files to Telegram servers it is my decision. I cannot understand how "Telegram" can be so "secure", more than WhatsApp but later, you cannot store and delete data from Telegram servers. It sounds to me very strange. Moreover, what if the cloud is hacked? What if it is erased? Years ago I was user of Grooveshark (music webpage). They had to close suddenly because of a judicial decision. They didn't say anything to users and neither they allowed you to download after closing the lists from users (but you could when it was working). Everyone who didn't export their playlists lost all of them. I don't want to feel again this.
4) In fact, I'd like to use secret chats but at the same time, being able to store my data.

**Comment by FrayxRulez** [comment]
Secret chats are supposed to be secure. How can they be if I allow you to export them to a plain text file?

**Comment by alskdjfj** [comment]
Are they more secured because they are "closed" in your phone/pc? Anyone who got access to your device will be able to get them, even if this option isn't there. Even if Alice or Bob want, they can show their messages to other people giving the opportunity to check their devices, getting screenshots or even taking a camera and taking pictures of the conversation. 

Secure conversation doesn't mean Alice or Bob can't have copies from their messages but that no Charlie will intercept them. Of course Charlie can break into your system and read any plain text that you have, but this is responsibility of Alice and Bob. You can always introduce the plain text into a 7z file secured by pass that user will know or use something like GNUPG. No?

Btw, I didn't pretend to be rude if anyone got offended by my answers.

**Comment by ferferga** [comment]
There are another specific tools/ways for this: https://github.com/tvdstaaij/telegram-history-dump

https://telegram.wiki/general/exporting-chats

**Comment by IlluminatiWave** [comment]
Almost a year has passed since this thread.

Currently official Telegram already supports the export of chat. I suppose it would be that it does not have much that came out yet do not want to introduce it, just as it can be a problem of Tlib, I say, if it is the case, just tell us and we will understand c:

I think it's about time 🤔

**Comment by PatrykMis** [comment]
I hope to see this feature in Unigram as official Telegram app has ability to do it but it is not accessible for visually impaired using screen readers.

**Comment by Simon818** [comment]
I accidentally found my way to this thread while trying to find a way to accomplish the same thing. A lot of the GitHub projects are quite abandoned and i'm not sure if any of them actually work anymore. It seems the only official way is to export chats using the desktop client, which I also cannot do.

**Comment by MarcAnt01** [comment]
> I accidentally found my way to this thread while trying to find a way to accomplish the same thing. A lot of the GitHub projects are quite abandoned and i'm not sure if any of them actually work anymore. It seems the only official way is to export chats using the desktop client, which I also cannot do.

Why? Telegram Desktop runs on every version of Windows :7””

**Comment by Simon818** [comment]
Because Telegram desktop is [very not accessible](https://github.com/telegramdesktop/tdesktop/issues/476) as previously stated. Last I checked, the screen reader sees a blank window. None of the custom controls have proper accessibility coded into them. It's a problem on all platforms but desktop is by far the worst.

**Comment by Elshara** [comment]
I would also add, that the current way desktop telegram implements this feature, lacks any usable information to work with. All it will do, is give an HTML5 text chat window with no links to interact with any existing message data. If I am a member of a group, and an admin decides one day to for whatever reason, accidentally or on purpose, remove my data without my consent...I have no way of knowing, cross referencing with an offline database any changes made to my data I already posted. So, anyone looking at it, deleting it, editing it, etc. No notification types of this crucial kind of data statistics are visible to me, and they should be. Because this is the kind of usable, workable and functional solution that will be able to give you peace of mind. Not only as a platform user, but as an online citizen in complete control of what data you do in fact post anywhere on telegram at least. And one of those important changes not only relies on controlling who can see exported data, but whether or not your post was referenced outside of its intended audience. Such as when containing messages was forwarded, and to whom, when, where and why. By whom, and how could this be preventable if necessary to ensure if you rely on telegram, there are no such security leaks that are as visibly obvious. Even when copying messages, you should be notified when this under-the-hood activity happens. Data exporting is the key to all of it. Because it's what you can control that happens to your data, which sets a precedent for what is possible with it and who can access it with your consent to freely do so.

**Comment by snowman** [comment]
feels bad
1. small UI & font size, not scale-able per app basis
2. `db.sqlite` is not parse-able, even I am the data owner, I have phone & SMS verification & password, no way

**Comment by x011** [comment]
> @alskdjfj Thats the point, this is a telegram side ability, ask them in twitter for this. Also telegram is a fully cloud based messenger why you need that? In WhatsApp may you need them but not in telegram

What about cases where an account expires or is blocked?

**Comment by x011** [comment]
> Can I ask you why? At least you could provide us a reasonable answer.

To backup user conversations.

**Comment by kefaslungu** [comment]
But can we at list do this with the API?

Even in 2025 screen readers are still not able to work with the official telegram app!

**Comment by Simon818** [comment]
I've looked for existing projects (though not in the last half-year). Most are either abandoned, or real time (they archive anything that comes in while the script is running, but don't pull history.) It's pretty frustrating to not only have an inaccessible desktop app but to have that app be the reason our chats are essentially held hostage. Not the responsibility of the Unigram devs, but after deliberately disabling ctrl+A I'm still frustrated.

**Comment by makisukurisu** [comment]
> ...but after deliberately disabling ctrl+A I'm still frustrated.

I'm not sure if this was a deliberate shortcut removal, but, in any case, it wasn't helping much, because there's a 100 message selection cap. (More than anything, it might've added to the frustration, if you scrolled through the entire chat, and Ctrl+A doesn't actually select all the messages)

Unigram might have been a bit more helpful to people selecting lots of messages by allowing to use Shift key to select all messages between the first selected and currently selected message. (Like it's done in Explorer, for example, however, since the selection is done with checkbox-like items, I'm not sure it's possible)

**Comment by PatrykMis** [comment]
I'm happy to donate, or we can set up a bounty on Bountysource. This isn't just a random feature request from one user - several of us have been asking for this over the past 7 years, and more people keep joining the conversation.

Like someone mentioned earlier, many solid projects end up abandoned just because someone started something and then lost interest. We'd really like to see this through.

The key question is: is anyone able to build and implement this, and would the devs/maintainers actually accept it?  
Even WhatsApp’s desktop and mobile clients support full export – including all files and attachments.

**Comment by FrayxRulez** [comment]
@PatrykMis Currently this feature is only implemented by TDesktop, this is quite a complex feature to have and it lives 100% client-side: Telegram servers provide some special feature to “initiate” an export session (thus to remove some limits on API calls frequency), but then it’s up to the app to export all the data to the right format chosen by the user. This feature has to be implemented in TDLib and not in Unigram, and since TDLib is open source, pull requests are welcome.
