### ISSUE TITLE
Inserting gif to chat from clipboard does not insert the gif as gif but as image

### ISSUE THREAD

**Issue by saibotma** [UnigramDev/Unigram#622]
Inserting gif in chat from clipboard does not insert the gif as gif but as image. The gif will be displayed as gif in the chatroom when adding it as an attachment.

**Comment by FrayxRulez** [comment]
Since commit https://github.com/UnigramDev/Unigram/commit/89967afe0d58c1378588069d49cd9d1c39e64d58 gifs are always sent as files: this way, if Telegram servers can, they will convert them to MP4, making them playable as gifs by all the clients, and if they can (eg, due to the file size) they will still be playable by opening the file externally

**Comment by FrayxRulez** [comment]
Maybe some day I'll add some in-app gif to mp4 conversion, but at the moment I really don't feel to %)
