### ISSUE TITLE
"My People" taskbar feature broken

### ISSUE THREAD

**Issue by adrianghc** [UnigramDev/Unigram#699]
A few releases ago Unigram's implementation of the "My People" feature on the taskbar has been broken - instead of showing the chat, there is simply a blank window with a hamburger button. Clicking it will open Unigram's regular menu but none of the options work.

**Comment by FrayxRulez** [comment]
Before opening a ticket you might want to check the existing ones already, including closed ones.

**Comment by adrianghc** [comment]
I missed checking the closed ones, you're right. I apologize for the inconvenience.

**Comment by FrayxRulez** [comment]
No problem, but there are like 3/4 closed issues already 😂

**Comment by MarcAnt01** [comment]
This feature looks to be loved by many people😂

**Comment by adrianghc** [comment]
Actually I barely use it (not Unigram's fault, though). Just something that I noticed and I thought it would be better if I didn't keep it to myself. 😉

**Comment by aliaspaj** [comment]
The "My People" taskbar feature is broken again. I don't know if it is because of the newest version of windows or the newest version of unigram.

My unigram is on the latest release: 3.9.2495.0
My Windows is also on the latest update: 1903 18362.145

I would love to have it back. It was my reason to use unigram.
