### ISSUE TITLE
Windows share´s ability to share directly to a contact e.g. myPeople should not open the app, but the chat

### ISSUE THREAD

**Issue by larsschellhas** [UnigramDev/Unigram#744]
Since Unigram is integrated into MyPeople it is possible to share something directly to a contact in the Windows 10 share menu. But if you then select Unigram as way to share the file/link/content to the contact Unigram opens in a normal window, following the normal share procedure, instead of showing the chat with the person directly in the share window, which should look like the myPeople chat window, pasting in the shared content.

**Comment by xperiandri** [comment]
Well, now it shares directly to the app.
Which is better then nothing.
However I cannot longer use other apps, because Unigram is first and share instantly goes to the app.
![image](https://user-images.githubusercontent.com/2365592/47259961-effad980-d4ba-11e8-878e-7fb08b808645.png)
It will be better to have hosted message compose experience inside share window.

**Comment by xperiandri** [comment]
@FrayxRulez, what do you think about my remark?

**Comment by FrayxRulez** [comment]
I'm thinking about a decent solution. Probably showing a confirmation button in the share window would be sufficient...

**Comment by FrayxRulez** [comment]
It is different as once you hit "send" in the email composer the window is closed and the upload happens in background

**Comment by xperiandri** [comment]
Can't you activate app then? On share window close.
That is why I asked if you can use TLib in Host and do RPC from UI app

**Comment by FrayxRulez** [comment]
Well, the process is the same, so using TDLib isn't a problem. The actual problem is the UX. Showing the chat page there would be confusing IMHO...

**Comment by xperiandri** [comment]
Not chat, but message composition view

**Comment by xperiandri** [comment]
Like for video or photo

**Comment by FrayxRulez** [comment]
Yeah that's possible. But what about files?

**Comment by xperiandri** [comment]
The best way would be to show a limited functionality chat.
Previous messages, message compose text box and send button.
User can only send message or close hosted view. No message selection, search, file picking and other stuff.

**Comment by FrayxRulez** [comment]
That's not an option

**Comment by xperiandri** [comment]
Then put a button "Open Unigram and send"

**Comment by FrayxRulez** [comment]
Closing this as My People is getting removed in 19H1

**Comment by xperiandri** [comment]
But the issue still remains because after I chose Unigram first time I no longer can share with another application when I share with a contact. Because UI just disappears and Unigram appears. Very annoying 😭😭😭
Is it so hard to show a message composition UI in a share window instead of redirecting to the app?

I remember we had a discussion about media uploading if app is not in the foreground. But we can check and if it is not, then launch it after a user pressed send.
