### ISSUE TITLE
Groups are not showing up in the People Bar

### ISSUE THREAD

**Issue by link6155** [UnigramDev/Unigram#754]
Contacts shows up as expected in the people bar, however group conversations do not show up.

**Comment by FrayxRulez** [comment]
To show a contact in the people bar it has to be synced with the system phonebook, and this can be done because Telegram expects this behavior and provides functionalities to implement this feature.

Groups however aren't designed to be synced with your phonebook (because, of course, they aren't contacts), so it isn't possible to implement this feature 😞

**Comment by link6155** [comment]
That makes sense, but would it not be possible to add an entire group as a entry in your contact list. MyTube, a UWP YouTube client, does this with channels. So channels you subscribe to shows up in your people list even though they aren't actually "contacts".

**Comment by MarcAnt01** [comment]
Personally, I have started using MyPeople functionality a week ago, but I think that adding groups there would make no sense, because MyPeople isn't thought for that

**Comment by link6155** [comment]
Yeah that is true, but it doesn't mean it can't be used like that. I think it should at least be an option as having quick access to group chats in the people bar is something I would use often.

**Comment by ferferga** [comment]
@MarcAnt01 There is no way to do it, as well. My people only support pinning stuff from the Contacts app in your system, and groups aren't inside your Contacts app.

**Comment by link6155** [comment]
I think you missed my point. You can unofficially support groups buy adding an entire group as a contact entry.

**Comment by FrayxRulez** [comment]
I think you missed my point: groups aren't designed to be synced.
Telegram offers a way to sync contacts: there's an API designed to do this, that allows me to keep _all_ of your contacts up to date.

The same doesn't apply to groups: there's no pratical way to keep them synced due to their nature of being non persistent
