### ISSUE TITLE
If closing main window with a chat open in another one, you can't open the app and launch home, neither by launching it

### ISSUE THREAD

**Issue by xperiandri** [UnigramDev/Unigram#843]

**Comment by FrayxRulez** [comment]
Looks like at the moment there's no APIs to recreate the main app window in a straightforward way. Marking this as blocked.

**Comment by anthroid** [comment]
Could this be resolved by just hiding the main window or minimizing it to the tray when clicking the [X]?

Maybe a setting to "Minimize main window to system tray", which would be functionally the same as closing it (only the independent chat window icon(s) would be left in the taskbar, the main window's icon would not), but the window would not technically be destroyed, only minimized/hidden? Then a menu item like "Show main window" on the independent chat's [...] menu could unhide the main window?

Seems this could be done if the following are possible:

- Minimize to system tray
- Override main window's [X] button to minimize to the tray instead of closing and destroying the window

Obviously, similar behavior could be accomplished by the user simply choosing to minimize the main window, but the behavior is unexpected that when the main window is closed, you can't get it back without losing your independent chat window (and also then losing its size and position).
