### ISSUE TITLE
Better implementation of enter in login page

### ISSUE THREAD

**Issue by ArmeF97** [UnigramDev/Unigram#937]
- [ ] move from Country code to phone number
- [x] trigger "start messaging"

**Comment by FrayxRulez** [comment]
I understood nothing :D

**Comment by MarcAnt01** [comment]
> I understood nothing :D

Will try to explain better both points:
1. Once I selected the country by pressing enter, the expected behaviour should be moving to the next field, which is the box where I can add phone number
2. Pressing enter should be the same as swiping left in the following page
![image](https://user-images.githubusercontent.com/43090263/52710932-dfea9680-2f90-11e9-848b-465cea32f832.png)

**Comment by ArmeF97** [comment]
Yeah, I really don't know why I written it in such uncomprensible way. I'm sorry

**Comment by MarcAnt01** [comment]
> Yeah, I really don't know why I written it in such uncomprensible way. I'm sorry

![image](https://user-images.githubusercontent.com/43090263/52712976-75d4f000-2f96-11e9-8a6b-e5c06ca34a50.png)
lol

**Comment by ArmeF97** [comment]
> 
> 
> > Yeah, I really don't know why I written it in such uncomprensible way. I'm sorry
> 
> ![image](https://user-images.githubusercontent.com/43090263/52712976-75d4f000-2f96-11e9-8a6b-e5c06ca34a50.png)
> lol

yeah, I edited my comment after I saw it was you LOL

**Comment by MarcAnt01** [comment]
Trigger "start messaging" fixed in latest version
